name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for raising a issue, and welcome to repo!'
        pr-message: 'Thanks for your first PR on my repo! 🎉 Will review it soon :)'
